language: node_js
node_js:
  - "node"
matrix:
  fast_finish: true
cache:
  directories:
    - "$HOME/.npm"
before_install:
  - npm install -g npm@latest
  - npm --version
install:
  - npm ci
script:
  - npm run test
