allowBuilds:
  esbuild: true
  unrs-resolver: true

autoInstallPeers: true

blockExoticSubdeps: true

enablePrePostScripts: false

engineStrict: true

minimumReleaseAge: 2880 # 2 days

minimumReleaseAgeExclude:
  - validate-package-exports@1.0.1
